##
## tgunzip  -  gzip decompressor example
##
## MinGW / Cygwin makefile
##
## Copyright (c) 1998-2003 by Joergen Ibsen / Jibz
## All Rights Reserved
##

target  = tgunzip.exe
objects = tgunzip.o
libs    = ../../lib/libtinf.a

cflags   = -s -Wall -Os -fomit-frame-pointer -I../../src
ldflags  = $(cflags)

.PHONY: all clean

all: $(target)

$(target): $(objects)
	gcc $(ldflags) -o $@ $^ $(libs)

%.o : %.c
	gcc $(cflags) -o $@ -c $<

clean:
	$(RM) $(target) $(objects)
