
{% render "scripts/helper/templates/copyright-liquid.yml" %}

{% if platforms == "all" -%}
  {% assign platforms = "linux-x64,linux-ia32,linux-arm64,linux-arm,darwin-x64,win32-x64,win32-ia32" -%}
{% endif -%}
{% assign platforms = platforms | split: "," -%}

# https://github.com/docker-library/official-images#architectures-other-than-amd64

# Debian versions: 
# - 8 jessie
# - 9 stretch
# - 10 buster

# Ubuntu releases
# - 12.04 LTS (Precise Pangolin)
# - 14.04 LTS (Trusty Tahr)
# - 16.04 LTS (Xenial Xerus)
# - 18.04 LTS (Bionic Beaver)
# - 20.04 LTS (Focal Fossa)

# -----------------------------------------------------------------------------

name: 'Test xPack {{ APP_NAME }} on Arm Docker platforms'

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'The folder part of the URL where binaries are stored'
        required: false
        default: 'release'
      version:
        description: 'The semver of the release'
        required: false
        default: 'current'

# The scripts are executed in the Docker context by GitHub Actions, 
# so `native-test.sh` should be fine, it already takes care of updates.
jobs:
{% for platform in platforms -%}
  {% case platform -%}
  {% when "linux-arm64" %}
  # https://en.wikipedia.org/wiki/Ubuntu_version_history
  # https://hub.docker.com/_/ubuntu
  # The ubuntu:12.04 image fails to update.
  ubuntu-arm64:
    name: 'arm64 {{ APP_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} test on Ubuntu 20, 18, 16, 14 stable'
    runs-on: [self-hosted, Linux, Arm64]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'Ubuntu 20.04 arm64'
        uses: docker://ubuntu:20.04
        with:
          entrypoint: /bin/bash
          args: /github/workspace/scripts/helper/tests/native-test.sh --image ubuntu:20.04 --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}
      - name: 'Ubuntu 18.04 arm64'
        uses: docker://ubuntu:18.04
        with:
          entrypoint: /bin/bash
          args: /github/workspace/scripts/helper/tests/native-test.sh --image ubuntu:18.04 --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}
      - name: 'Ubuntu 16.04 arm64'
        uses: docker://ubuntu:16.04
        with:
          entrypoint: /bin/bash
          args: /github/workspace/scripts/helper/tests/native-test.sh --image ubuntu:16.04 --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}

  # https://en.wikipedia.org/wiki/Debian_version_history
  # https://hub.docker.com/_/debian
  debian-arm64:
    name: 'arm64 {{ APP_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} test on Debian 10, 9, 8 stable'
    runs-on: [self-hosted, Linux, Arm64]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'Debian 10 arm64'
        uses: docker://debian:buster
        with:
          entrypoint: /bin/bash
          args: /github/workspace/scripts/helper/tests/native-test.sh --image debian:buster --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}
      - name: 'Debian 9 arm64'
        uses: docker://debian:stretch
        with:
          entrypoint: /bin/bash
          args: /github/workspace/scripts/helper/tests/native-test.sh --image debian:stretch --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}
      # docker://debian:jessie has no 64-bit variant

  # End of life. See RedHat.
  # https://en.wikipedia.org/wiki/CentOS
  # https://hub.docker.com/_/centos
  # `-static` disabled, there is no static libc.a.
  centos-arm64:
    name: 'arm64 {{ APP_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} test on CentOS 8, 7 stable'
    runs-on: [self-hosted, Linux, Arm64]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'CentOS 8 arm64'
        uses: docker://centos:8
        with:
          entrypoint: /bin/bash
          args: /github/workspace/scripts/helper/tests/native-test.sh --image centos:8 --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}
      # docker://centos:7 - undefined reference to `__cxa_thread_atexit_impl@GLIBC_2.18'


  # https://hub.docker.com/r/redhat/ubi8
  # `-static` disabled, there is no static libc.a.
  redhat-arm64:
    name: 'arm64 {{ APP_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} test on RedHat 8 stable'
    runs-on: [self-hosted, Linux, Arm64]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'RedHat 8 arm64'
        uses: docker://redhat/ubi8
        with:
          entrypoint: /bin/bash
          args: /github/workspace/scripts/helper/tests/native-test.sh --image redhat/ubi8 --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}

  # https://en.wikipedia.org/wiki/OpenSUSE#Releases
  # https://hub.docker.com/u/opensuse
  # `-static` disabled, there is no static libc.a.
  opensuse-arm64:
    name: 'arm64 {{ APP_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} test on OpenSUSE 15, 13 stable'
    runs-on: [self-hosted, Linux, Arm64]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'OpenSUSE 15 arm64'
        uses: docker://opensuse/leap:15.3
        with:
          entrypoint: /bin/bash
          args: /github/workspace/scripts/helper/tests/native-test.sh --image opensuse/leap:15.3 --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}
      # docker://opensuse/leap:13 not available

  # https://en.wikipedia.org/wiki/Fedora_version_history
  # https://hub.docker.com/_/fedora
  # `-static` disabled, there is no static libc.a.
  fedora-arm64:
    name: 'arm64 {{ APP_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} test on Fedora 34, 32, 30, 27 stable'
    runs-on: [self-hosted, Linux, Arm64]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'Fedora 34 arm64'
        uses: docker://fedora:34
        with:
          entrypoint: /bin/bash
          args: /github/workspace/scripts/helper/tests/native-test.sh --image fedora:34 --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}
      - name: 'Fedora 32 arm64'
        uses: docker://fedora:32
        with:
          entrypoint: /bin/bash
          args: /github/workspace/scripts/helper/tests/native-test.sh --image fedora:32 --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}
      - name: 'Fedora 30 arm64'
        uses: docker://fedora:30
        with:
          entrypoint: /bin/bash
          args: /github/workspace/scripts/helper/tests/native-test.sh --image fedora:30 --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}
      - name: 'Fedora 27 arm64'
        uses: docker://fedora:27
        with:
          entrypoint: /bin/bash
          args: /github/workspace/scripts/helper/tests/native-test.sh --image fedora:27 --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}

  # fedora-arm: fails to update

  # ---------------------------------------------------------------------------

  ubuntu-arm64-latest:
    name: 'arm64 {{ APP_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} test on Ubuntu latest'
    runs-on: [self-hosted, Linux, Arm64]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'Ubuntu latest arm64'
        uses: docker://ubuntu:latest
        with:
          entrypoint: /bin/bash
          args: /github/workspace/scripts/helper/tests/native-test.sh --image ubuntu:latest --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}
      # ubuntu:rolling fails during update

  debian-arm64-latest:
    name: 'arm64 {{ APP_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} test on Debian latest'
    runs-on: [self-hosted, Linux, Arm64]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'Debian testing arm64'
        uses: docker://debian:testing
        with:
          entrypoint: /bin/bash
          args: /github/workspace/scripts/helper/tests/native-test.sh --image debian:testing --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}
      - name: 'Debian latest arm64'
        uses: docker://debian:latest
        with:
          entrypoint: /bin/bash
          args: /github/workspace/scripts/helper/tests/native-test.sh --image debian:latest --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}


  # - https://hub.docker.com/r/opensuse/tumbleweed
  opensuse-arm64-latest:
    name: 'arm64 {{ APP_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} test on OpenSUSE latest'
    runs-on: [self-hosted, Linux, Arm64]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'OpenSUSE tumbleweed arm64'
        uses: docker://opensuse/tumbleweed
        with:
          entrypoint: /bin/bash
          args: /github/workspace/scripts/helper/tests/native-test.sh --image opensuse/tumbleweed --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}

  # fedora:rawhide - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/...
  # docker://fedora:latest

  # docker://archlinux:latest - has no Arm variants

  # - https://hub.docker.com/u/manjarolinux
  # docker://manjarolinux/base - too slow

  # - https://hub.docker.com/r/gentoo/portage
  # docker://gentoo/portage - exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown.

  {% when "linux-arm" %}
  # https://hub.docker.com/r/arm32v7/ubuntu/
  ubuntu-arm:
    name: 'arm {{ APP_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} test on Ubuntu 18, 16, 14 stable'
    runs-on: [self-hosted, Linux, Arm64]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      # docker://arm32v7/ubuntu:20.04 - fails to update
      - name: 'Ubuntu 18.04 arm'
        uses: docker://arm32v7/ubuntu:18.04
        with:
          entrypoint: /usr/bin/linux32
          args: /bin/bash /github/workspace/scripts/helper/tests/native-test.sh --image arm32v7/ubuntu:18.04 --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}
      - name: 'Ubuntu 16.04 arm'
        uses: docker://arm32v7/ubuntu:16.04
        with:
          entrypoint: /usr/bin/linux32
          args: /bin/bash /github/workspace/scripts/helper/tests/native-test.sh --image arm32v7/ubuntu:16.04 --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}

  # https://hub.docker.com/r/arm32v7/debian
  debian-arm:
    name: 'arm {{ APP_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} test on Debian 10, 9, 8 stable'
    runs-on: [self-hosted, Linux, Arm64]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'Debian 10 arm'
        uses: docker://arm32v7/debian:buster
        with:
          entrypoint: /usr/bin/linux32
          args: /bin/bash /github/workspace/scripts/helper/tests/native-test.sh --image arm32v7/debian:buster --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}
      - name: 'Debian 9 arm'
        uses: docker://arm32v7/debian:stretch
        with:
          entrypoint: /usr/bin/linux32
          args: /bin/bash /github/workspace/scripts/helper/tests/native-test.sh --image arm32v7/debian:stretch --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}
      - name: 'Debian 8 arm'
        uses: docker://arm32v7/debian:jessie
        with:
          entrypoint: /usr/bin/linux32
          args: /bin/bash /github/workspace/scripts/helper/tests/native-test.sh --image arm32v7/debian:jessie --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}

  # docker://arm32v7/debian:testing - fails to update

  raspbian-arm:
    name: 'arm {{ APP_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} test on Raspbian 9 stable'
    runs-on: [self-hosted, Linux, Arm64]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'Raspbian 9 arm'
        uses: docker://raspbian/stretch
        with:
          entrypoint: /usr/bin/linux32
          args: /bin/bash /github/workspace/scripts/helper/tests/native-test.sh --image raspbian/stretch --version {% raw %}${{ github.event.inputs.version }}{% endraw %} --base-url {% raw %}${{ github.event.inputs.base_url }}{% endraw %}
      # docker://raspbian/jessie (8) fails to update.

  # https://hub.docker.com/r/arm32v7/centos
  # docker://arm32v7/centos:7 - fails to update
  # docker://arm32v7/centos:8 - not available

  # centos:latest outdated
  # docker://arm32v7/centos:latest outdated
  {% endcase -%}
{% endfor %}

# -----------------------------------------------------------------------------
