name: FW Build / Test

on: [push, pull_request]

jobs:
  determine-builds:
    name: Evaluate Required Builds
    runs-on: ubuntu-latest
    timeout-minutes: 1
    # Map a step output to job output
    outputs:

      esp32-ap: ${{ steps.filter.outputs.esp32-ap }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          # TODO: work around issue with paths-filter (https://github.com/dorny/paths-filter/issues/227)
          token: ''
          filters: .github/path-filters.yml


  ap-build:
    name: Build AP FW
    needs: [determine-builds]
    if: ${{ needs.determine-builds.outputs.esp32-ap == 'true' }}
    strategy:
      matrix:
        environment:
          #- OpenEPaperLink_Mini_AP
          #- OpenEPaperLink_AP_and_Flasher
          - ESP32_S3_16_8_MAKARON_AP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pio

      - name: Build ${{ matrix.environment }} binary
        run: |
          cd ESP32_AP-Flasher
          pio run --environment ${{ matrix.environment }}
      - name: Build ${{ matrix.environment }} filesystem
        if: ${{ matrix.environment != 'OpenEPaperLink_ESP32-PoE-ISO_AP' }}
        run: |
          cd ESP32_AP-Flasher
          pio run --target buildfs --environment ${{ matrix.environment }}



